create table users (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    email varchar(255) not null unique,
    phone varchar(255) not null,
    password_hash varchar(255) not null,
    role varchar(255) not null check (role in ('ADMIN', 'MANAGER', 'TRAINER', 'CLIENT')),
    created_at timestamp(6) not null,
    enabled boolean not null
);

create table administrator (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    position varchar(255),
    constraint fk_administrator_user foreign key (user_id) references users (id)
);

create table client (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    registration_date date not null,
    rfid_card varchar(255) unique,
    birth_date date,
    constraint fk_client_user foreign key (user_id) references users (id)
);

create table trainer (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    specialization varchar(255),
    years_of_experience integer not null,
    description varchar(1000),
    constraint fk_trainer_user foreign key (user_id) references users (id)
);

create table hall (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    capacity integer not null,
    description varchar(1000)
);

create table membership_type (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    duration_days integer not null,
    visit_count integer,
    price numeric(38, 2) not null,
    description varchar(1000),
    active boolean not null,
    freeze_allowed boolean not null,
    max_freeze_days integer not null
);

create table training_type (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    duration_minutes integer not null,
    description varchar(1000),
    color varchar(255)
);

create table membership (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    membership_type_id bigint not null,
    purchase_date date not null,
    activation_date date not null,
    expiration_date date not null,
    remaining_visits integer,
    status varchar(255) not null check (status in ('ACTIVE', 'EXPIRED', 'FROZEN', 'CANCELLED', 'DEPLETED')),
    constraint fk_membership_client foreign key (client_id) references client (id),
    constraint fk_membership_type foreign key (membership_type_id) references membership_type (id)
);

create table schedule (
    id bigint generated by default as identity primary key,
    training_type_id bigint not null,
    trainer_id bigint not null,
    hall_id bigint not null,
    date date not null,
    start_time time(6) not null,
    end_time time(6) not null,
    participant_limit integer not null,
    status varchar(255) not null check (status in ('PLANNED', 'COMPLETED', 'CANCELLED')),
    trainer_comment varchar(1000),
    constraint fk_schedule_training_type foreign key (training_type_id) references training_type (id),
    constraint fk_schedule_trainer foreign key (trainer_id) references trainer (id),
    constraint fk_schedule_hall foreign key (hall_id) references hall (id)
);

create table booking (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    schedule_id bigint not null,
    booking_date_time timestamp(6) not null,
    status varchar(255) not null check (status in ('ACTIVE', 'CANCELLED', 'ATTENDED', 'NO_SHOW')),
    constraint uk_booking_client_schedule unique (client_id, schedule_id),
    constraint fk_booking_client foreign key (client_id) references client (id),
    constraint fk_booking_schedule foreign key (schedule_id) references schedule (id)
);

create table membership_freeze (
    id bigint generated by default as identity primary key,
    membership_id bigint not null,
    start_date date not null,
    end_date date not null,
    reason varchar(500),
    status varchar(255) not null check (status in ('SCHEDULED', 'ACTIVE', 'FINISHED', 'CANCELLED')),
    constraint fk_membership_freeze_membership foreign key (membership_id) references membership (id)
);

create table membership_purchase_request (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    membership_type_id bigint not null,
    created_at timestamp(6) not null,
    desired_activation_date date,
    comment varchar(500),
    status varchar(255) not null check (status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    decided_by_id bigint,
    decided_at timestamp(6),
    decision_comment varchar(500),
    created_membership_id bigint,
    constraint fk_purchase_request_client foreign key (client_id) references client (id),
    constraint fk_purchase_request_membership_type foreign key (membership_type_id) references membership_type (id),
    constraint fk_purchase_request_decided_by foreign key (decided_by_id) references users (id),
    constraint fk_purchase_request_membership foreign key (created_membership_id) references membership (id)
);

create table notification (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(255) not null,
    message varchar(1500) not null,
    type varchar(255) not null check (type in ('BOOKING', 'SCHEDULE', 'MEMBERSHIP', 'SYSTEM')),
    channel varchar(255) not null check (channel in ('IN_APP', 'EMAIL', 'SMS', 'PUSH')),
    delivery_status varchar(255) not null check (delivery_status in ('SCHEDULED', 'SENT', 'FAILED')),
    read_status boolean not null,
    created_at timestamp(6) not null,
    sent_at timestamp(6),
    constraint fk_notification_user foreign key (user_id) references users (id)
);

create table sale (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    membership_id bigint not null unique,
    amount numeric(38, 2) not null,
    payment_method varchar(255) not null check (payment_method in ('CASH', 'CARD', 'ONLINE')),
    payment_date timestamp(6) not null,
    status varchar(255) not null check (status in ('PAID', 'CANCELLED', 'REFUNDED')),
    constraint fk_sale_client foreign key (client_id) references client (id),
    constraint fk_sale_membership foreign key (membership_id) references membership (id)
);

create table visit (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    membership_id bigint,
    schedule_id bigint,
    visit_time timestamp(6) not null,
    visit_type varchar(255) not null check (visit_type in ('GYM', 'GROUP_TRAINING', 'ONE_TIME')),
    constraint fk_visit_client foreign key (client_id) references client (id),
    constraint fk_visit_membership foreign key (membership_id) references membership (id),
    constraint fk_visit_schedule foreign key (schedule_id) references schedule (id)
);